server.port: 9004
spring:
  application:
    name: scalable-board-hot-article-service
  data:
    redis:
      host: 127.0.0.1
      port: 16379
  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: scalable-board-hot-article-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    listener:
      ack-mode: manual
endpoints:
  scalable-board-article-service:
    url: http://127.0.0.1:9000
